/**
 * Australia Eligible Occupation List (691 Roles)
 * Categorised into 11 broad sectors for Australia Employer Sponsored Work Visa.
 */

export const CATEGORIZED_OCCUPATIONS: Record<string, string[]> = {
  "Healthcare & Medical (108 roles)": [
    "Aboriginal and Torres Strait Islander Health Worker",
    "Advertising Specialist",
    "Audiologist",
    "Beauty Therapist",
    "Biomedical Engineer",
    "Cardiothoracic Surgeon",
    "Chiropractor",
    "Clinical Psychologist",
    "Complementary Health Therapists nec",
    "Cyber Governance Risk and Compliance Specialist",
    "Cyber Security Advice and Assessment Specialist",
    "Dental Hygienist",
    "Dental Prosthetist",
    "Dental Specialist",
    "Dental Technician",
    "Dental Therapist",
    "Dentist",
    "Diagnostic and Interventional Radiologist",
    "Dietitian",
    "Director (Film, Television, Radio or Stage)",
    "Diversional Therapist",
    "Educational Psychologist",
    "Emergency Medicine Specialist",
    "Enrolled Nurse",
    "Environmental Health Officer",
    "Exercise Physiologist",
    "Film, Television, Radio and Stage Directors nec",
    "General Practitioner",
    "Health and Welfare Services Managers nec",
    "Health Diagnostic and Promotion Professionals nec",
    "Health Information Manager",
    "Health Practice Manager",
    "Health Promotion Officer",
    "Hospital Pharmacist",
    "ICT Security Specialist",
    "Industrial Pharmacist",
    "Intensive Care Ambulance Paramedic",
    "Intensive Care Specialist",
    "Marketing Specialist",
    "Massage Therapist",
    "Medical Administrator",
    "Medical Diagnostic Radiographer",
    "Medical Laboratory Scientist",
    "Medical Laboratory Technician",
    "Medical Oncologist",
    "Medical Practitioners nec",
    "Medical Radiation Therapist",
    "Medical Technicians nec",
    "Midwife",
    "Mothercraft Nurse",
    "Multimedia Specialist",
    "Neurosurgeon",
    "Nurse Educator",
    "Nurse Manager",
    "Nurse Practitioner",
    "Nurse Researcher",
    "Nurseryperson",
    "Occupational Health and Safety Adviser",
    "Occupational Therapist",
    "Ophthalmologist",
    "Optometrist",
    "Organisational Psychologist",
    "Orthopaedic Surgeon",
    "Osteopath",
    "Paediatric Surgeon",
    "Pathologist",
    "Pharmacy Technician",
    "Physiotherapist",
    "Plastic and Reconstructive Surgeon",
    "Primary Health Organisation Manager",
    "Program Director (Television or Radio)",
    "Psychiatrist",
    "Psychologists nec",
    "Psychotherapist",
    "Radiation Oncologist",
    "Radio Journalist",
    "Radio Presenter",
    "Radiocommunications Technician",
    "Registered Nurse (Aged Care)",
    "Registered Nurse (Child and Family Health)",
    "Registered Nurse (Community Health)",
    "Registered Nurse (Critical Care and Emergency)",
    "Registered Nurse (Developmental Disability)",
    "Registered Nurse (Disability and Rehabilitation)",
    "Registered Nurse (Medical Practice)",
    "Registered Nurse (Medical)",
    "Registered Nurse (Mental Health)",
    "Registered Nurse (Paediatrics)",
    "Registered Nurse (Perioperative)",
    "Registered Nurse (Surgical)",
    "Registered Nurses nec",
    "Renal Medicine Specialist",
    "Resident Medical Officer",
    "Residential Care Officer",
    "Retail Pharmacist",
    "Sales Representative (Medical and Pharmaceutical Products)",
    "Saw Doctor",
    "Sonographer",
    "Specialist Managers nec",
    "Specialist Physician (General Medicine)",
    "Specialist Physicians nec",
    "Speech Pathologist",
    "Student Counsellor",
    "Surgeon (General)",
    "Thoracic Medicine Specialist",
    "Traditional Chinese Medicine Practitioner",
    "Vascular Surgeon",
    "Veterinary Nurse",
  ],

  "Information Technology & Cyber (54 roles)": [
    "Analyst Programmer",
    "Architect",
    "Architectural Draftsperson",
    "Architectural, Building and Surveying Technicians nec",
    "Cabler (Data and Telecommunications)",
    "Computer Network and Systems Engineer",
    "Cyber Security Analyst",
    "Cyber Security Architect",
    "Cyber Security Engineer",
    "Cyber Security Operations Coordinator",
    "Data Analyst",
    "Data Scientist",
    "Database Administrator",
    "Developer Programmer",
    "DevOps Engineer",
    "ICT Account Manager",
    "ICT Business Analyst",
    "ICT Business Development Manager",
    "ICT Customer Support Officer",
    "ICT Managers nec",
    "ICT Project Manager",
    "ICT Quality Assurance Engineer",
    "ICT Sales Representative",
    "ICT Support and Test Engineers nec",
    "ICT Support Engineer",
    "ICT Support Technicians nec",
    "ICT Systems Test Engineer",
    "ICT Trainer",
    "Landscape Architect",
    "Market Research Analyst",
    "Naval Architect",
    "Network Administrator",
    "Network Analyst",
    "Organisation and Methods Analyst",
    "Picture Framer",
    "Policy Analyst",
    "Security Consultant",
    "Software and Applications Programmers nec",
    "Software Engineer",
    "Software Tester",
    "Supply Chain Analyst",
    "Systems Administrator",
    "Systems Analyst",
    "Telecommunications Cable Jointer",
    "Telecommunications Engineer",
    "Telecommunications Field Engineer",
    "Telecommunications Linesworker",
    "Telecommunications Network Engineer",
    "Telecommunications Network Planner",
    "Telecommunications Technical Officer or Technologist",
    "Telecommunications Technician",
    "Web Administrator",
    "Web Designer",
    "Web Developer",
  ],

  "Engineering & Technical (97 roles)": [
    "Aeronautical Engineer",
    "Agricultural and Agritech Technician",
    "Agricultural Engineer",
    "Agricultural Technician",
    "Airconditioning and Mechanical Services Plumber",
    "Airconditioning and Refrigeration Mechanic",
    "Aircraft Maintenance Engineer (Avionics)",
    "Aircraft Maintenance Engineer (Mechanical)",
    "Aircraft Maintenance Engineer (Structures)",
    "Anaesthetic Technician",
    "Animal Husbandry Technician",
    "Aquaculture or Fisheries Technician",
    "Automotive Electrician",
    "Biotechnologist",
    "Boat Builder and Repairer",
    "Building and Engineering Technicians nec",
    "Business Machine Mechanic",
    "Cardiac Technician",
    "Chemical Engineer",
    "Chemistry Technician",
    "Civil Engineer",
    "Civil Engineering Draftsperson",
    "Civil Engineering Technician",
    "Construction Estimator",
    "Construction Project Manager",
    "Diesel Motor Mechanic",
    "Earth Science Technician",
    "Electrical Engineer",
    "Electrical Engineering Draftsperson",
    "Electrical Engineering Technician",
    "Electrical Linesworker",
    "Electrician (General)",
    "Electrician (Special Class)",
    "Electronic Engineering Draftsperson",
    "Electronic Engineering Technician",
    "Electronics Engineer",
    "Engineering Manager",
    "Engineering Patternmaker",
    "Engineering Professionals nec",
    "Engineering Technologist",
    "Environmental Engineer",
    "Fire Protection Equipment Technician",
    "Fire Protection Plumber",
    "Fitter (General)",
    "Fitter and Turner",
    "Fitter-Welder",
    "Food Technologist",
    "Gallery or Museum Technician",
    "Gas or Petroleum Operator",
    "Gasfitter",
    "Geotechnical Engineer",
    "Hardware Technician",
    "Industrial Engineer",
    "Insurance Risk Surveyor",
    "Irrigation Technician",
    "Library Technician",
    "Life Science Technician",
    "Lift Mechanic",
    "Light Technician",
    "Marine Surveyor",
    "Materials Engineer",
    "Mechanical Engineer",
    "Mechanical Engineering Draftsperson",
    "Mechanical Engineering Technician",
    "Metal Fitters and Machinists nec",
    "Metallurgical or Materials Technician",
    "Mining Engineer (excluding Petroleum)",
    "Motor Mechanic (General)",
    "Motorcycle Mechanic",
    "Nuclear Medicine Technologist",
    "Operating Theatre Technician",
    "Optical Mechanic",
    "Other Draftsperson",
    "Performing Arts Technicians nec",
    "Petroleum Engineer",
    "Plastics Technician",
    "Plumber (General)",
    "Pressure Welder",
    "Production Manager (Mining)",
    "Production or Plant Engineer",
    "Project Builder",
    "Quantity Surveyor",
    "Respiratory Technician",
    "Roof Plumber",
    "School Laboratory Technician",
    "Science Technicians nec",
    "Ship's Engineer",
    "Small Engine Mechanic",
    "Sound Technician",
    "Structural Engineer",
    "Surveying or Spatial Science Technician",
    "Surveyor",
    "Technicians and Trades Workers nec",
    "Textile, Clothing and Footwear Mechanic",
    "Transport Engineer",
    "Vehicle Body Builder",
    "Welder (First Class)",
  ],

  "Education & Training (28 roles)": [
    "Animal Attendants and Trainers nec",
    "Art Teacher (Private Tuition)",
    "Dance Teacher (Private Tuition)",
    "Dog Handler or Trainer",
    "Drama Teacher (Private Tuition)",
    "Early Childhood (Pre-primary School) Teacher",
    "Education Adviser",
    "Education Managers nec",
    "Education Reviewer",
    "Faculty Head",
    "First Aid Trainer",
    "Horse Trainer",
    "Middle School Teacher",
    "Music Teacher (Private Tuition)",
    "Out of School Hours Care Worker",
    "Primary School Teacher",
    "Private Tutors and Teachers nec",
    "Regional Education Manager",
    "School Principal",
    "Secondary School Teacher",
    "Special Education Teachers nec",
    "Special Needs Teacher",
    "Teacher of English to Speakers of Other Languages (TESOL Teacher)",
    "Teacher of the Hearing Impaired",
    "Teacher of the Sight Impaired",
    "University Lecturer",
    "University Tutor",
    "Vocational Education Teacher",
  ],

  "Business, Finance & Management (98 roles)": [
    "Accommodation and Hospitality Managers nec",
    "Accountant (General)",
    "Advertising Manager",
    "Agricultural Consultant",
    "Ambulance Officer",
    "Amusement Centre Manager",
    "Arts Administrator or Manager",
    "Betting Agency Manager",
    "Business Broker",
    "Cafe or Restaurant Manager",
    "Call or Contact Centre Manager",
    "Caravan Park and Camping Ground Manager",
    "Chief Information Officer",
    "Child Care Centre Manager",
    "Cinema or Theatre Manager",
    "Company Secretary",
    "Conservation Officer",
    "Content Creator (Marketing)",
    "Contract Administrator",
    "Corporate General Manager",
    "Corporate Services Manager",
    "Corporate Treasurer",
    "Court Bailiff or Sheriff (Aus) / Court Collections Officer (NZ)",
    "Court Orderly (Aus) / Court Registry Officer (NZ)",
    "Customer Service Manager",
    "Disabilities Services Officer",
    "Economist",
    "Electorate Officer",
    "Environmental Consultant",
    "Environmental Manager",
    "Equipment Hire Manager",
    "External Auditor",
    "Facilities Manager",
    "Finance Broker",
    "Finance Manager",
    "Financial Brokers nec",
    "Financial Dealers nec",
    "Financial Institution Branch Manager",
    "Financial Investment Adviser",
    "Financial Investment Manager",
    "Financial Market Dealer",
    "Fisheries Officer",
    "Fitness Centre Manager",
    "Fleet Manager",
    "Hair or Beauty Salon Manager",
    "Hospitality, Retail and Service Managers nec",
    "Hotel or Motel Manager",
    "Hotel Service Manager",
    "Human Resource Adviser",
    "Human Resource Manager",
    "Insurance Broker",
    "Internal Auditor",
    "Laboratory Manager",
    "Land Economist",
    "Legal Secretary",
    "Liaison Officer",
    "Licensed Club Manager",
    "Management Accountant",
    "Management Consultant",
    "Migration Agent (Aus) / Immigration Consultant (NZ)",
    "Office Manager",
    "Policy and Planning Manager",
    "Post Office Manager",
    "Practice Managers nec",
    "Primary Products Assurance and Inspection Officers nec",
    "Primary Products Quality Assurance Officer",
    "Procurement Manager",
    "Production Manager (Forestry)",
    "Production Manager (Manufacturing)",
    "Program or Project Administrator",
    "Property Manager",
    "Public Relations Manager",
    "Quality Assurance Manager",
    "Quarantine Officer",
    "Railway Station Manager",
    "Records Manager",
    "Recreation Officer",
    "Recruitment Consultant",
    "Regulatory Affairs Manager",
    "Research and Development Manager",
    "Retail Manager (General)",
    "Retirement Village Manager",
    "Sales and Marketing Manager",
    "Sales Representative (Industrial Products)",
    "Secretary (General)",
    "Ship's Officer",
    "Sports Administrator",
    "Sports Centre Manager",
    "Sports Development Officer",
    "Stage Manager",
    "Supply and Distribution Manager",
    "Taxation Accountant",
    "Technical Sales Representatives nec",
    "Transport Company Manager",
    "Travel Agency Manager",
    "Travel Consultant",
    "Trust Officer",
    "Welfare Centre Manager",
  ],

  "Hospitality, Tourism & Service (8 roles)": [
    "Chef",
    "Conference and Event Organiser",
    "Cook",
    "Flight Attendant",
    "Hairdresser",
    "Pastrycook",
    "Tour Guide",
    "Travel Attendants nec",
  ],

  "Agriculture, Environment & Science (40 roles)": [
    "Agricultural Research Scientist",
    "Agricultural Scientist",
    "Aquaculture Farmer",
    "Aquaculture or Fisheries Scientist",
    "Beef Cattle Farmer",
    "Botanist",
    "Cotton Grower",
    "Crop Farmers nec",
    "Dairy Cattle Farmer",
    "Deer Farmer",
    "Environmental Research Scientist",
    "Environmental Scientists nec",
    "Flower Grower",
    "Forester",
    "Fruit or Nut Grower",
    "Geologist",
    "Goat Farmer",
    "Grain, Oilseed or Pasture Grower",
    "Grape Grower",
    "Hydrogeologist",
    "Life Scientist (General)",
    "Life Scientists nec",
    "Livestock Farmers nec",
    "Marine Biologist",
    "Master Fisher",
    "Meteorologist",
    "Microbiologist",
    "Mixed Crop and Livestock Farmer",
    "Mixed Crop Farmer",
    "Mixed Livestock Farmer",
    "Other Spatial Scientist",
    "Pig Farmer",
    "Poultry Farmer",
    "Respiratory Scientist",
    "Sheep Farmer",
    "Sugar Cane Grower",
    "Turf Grower",
    "Vegetable Grower",
    "Veterinarian",
    "Zoologist",
  ],

  "Arts, Media & Creative (38 roles)": [
    "Actor",
    "Actors, Dancers and Other Entertainers nec",
    "Art Director (Film, Television or Stage)",
    "Artistic Director",
    "Camera Operator (Film, Television or Video)",
    "Chief Executive or Managing Director",
    "Composer",
    "Copywriter",
    "Director of Photography",
    "Entertainer or Variety Artist",
    "Fashion Designer",
    "Film and Video Editor",
    "Funeral Director",
    "Graphic Designer",
    "Illustrator",
    "Industrial Designer",
    "Interior Designer",
    "Irrigation Designer",
    "Jewellery Designer",
    "Journalists and Other Writers nec",
    "Make Up Artist",
    "Media Producer (excluding Video)",
    "Multimedia Designer",
    "Music Director",
    "Music Professionals nec",
    "Musical Instrument Maker or Repairer",
    "Musician (Instrumental)",
    "Nursing Clinical Director",
    "Photographer",
    "Photographer's Assistant",
    "Potter or Ceramic Artist",
    "Print Journalist",
    "Signwriter",
    "Technical Director",
    "Technical Writer",
    "Television Equipment Operator",
    "Television Journalist",
    "Television Presenter",
  ],

  "Legal, Community & Government (16 roles)": [
    "Barrister",
    "Careers Counsellor",
    "Clerk of Court",
    "Community Arts Worker",
    "Community Worker",
    "Counsellors nec",
    "Drug and Alcohol Counsellor",
    "Family and Marriage Counsellor",
    "Intellectual Property Lawyer",
    "Judicial and Other Legal Professionals nec",
    "Law Clerk",
    "Legal Executive",
    "Rehabilitation Counsellor",
    "Social Worker",
    "Solicitor",
    "Welfare Worker",
  ],

  "Trades & Manufacturing (39 roles)": [
    "Bricklayer",
    "Butcher or Smallgoods Maker",
    "Cabinet Maker",
    "Cabinetmaker",
    "Canvas Goods Fabricator",
    "Carpenter",
    "Carpenter and Joiner",
    "Clothing Patternmaker",
    "Dressmaker or Tailor",
    "Fibrous Plasterer",
    "Furniture Maker",
    "Leather Goods Maker",
    "Metal Casting Trades Worker",
    "Metal Fabricator",
    "Metal Machinist (First Class)",
    "Metal Polisher",
    "Metallurgist",
    "Plasterer (Wall and Ceiling)",
    "Precision Instrument Maker and Repairer",
    "Print Finisher",
    "Printing Machinist",
    "Renderer (Solid Plaster)",
    "Roof Tiler",
    "Sail Maker",
    "Screen Printer",
    "Sheetmetal Trades Worker",
    "Sheetmetal Worker",
    "Shoemaker",
    "Small Offset Printer",
    "Solid Plasterer",
    "Toolmaker",
    "Vehicle Painter",
    "Vehicle Trimmer",
    "Wall and Floor Tiler",
    "Watch and Clock Maker and Repairer",
    "Wine Maker",
    "Wood Machinist",
    "Wood Machinists and Other Wood Trades Workers nec",
    "Wood Turner",
  ],

  "Other Occupations (165 roles)": [
    "Actuary",
    "Acupuncturist",
    "Aeroplane Pilot",
    "Agronomist",
    "Air Transport Professionals nec",
    "Anaesthetist",
    "Antique Dealer",
    "Apiarist",
    "Apparel Cutter",
    "Arborist",
    "Archaeologist",
    "Archivist",
    "Auctioneer",
    "Author",
    "Baker",
    "Bed and Breakfast Operator",
    "Biochemist",
    "Blacksmith",
    "Boarding Kennel or Cattery Operator",
    "Book or Script Editor",
    "Broadcast Transmitter Operator",
    "Building Associate",
    "Building Inspector",
    "Call or Contact Centre Team Leader",
    "Cardiologist",
    "Cartographer",
    "Chemical Plant Operator",
    "Chemist",
    "Child Care Worker",
    "Child Care Worker (group leaders only)",
    "Clinical Coder",
    "Clinical Haematologist",
    "Clothing Trades Workers nec",
    "Commodities Trader",
    "Communications Operator",
    "Conservator",
    "Conveyancer",
    "Dancer or Choreographer",
    "Dermatologist",
    "Diver",
    "Diving Instructor (Open Water)",
    "Dog or Horse Racing Official",
    "Drainer",
    "Driving Instructor",
    "Electronic Equipment Trades Worker",
    "Electronic Instrument Trades Worker (General)",
    "Electronic Instrument Trades Worker (Special Class)",
    "Electroplater",
    "Emergency Service Worker",
    "Endocrinologist",
    "Engraver",
    "Entomologist",
    "Family Support Worker",
    "Farrier",
    "Floor Finisher",
    "Florist",
    "Flying Instructor",
    "Footballer",
    "Funeral Workers nec",
    "Furniture Finisher",
    "Futures Trader",
    "Gallery or Museum Curator",
    "Gardener (General)",
    "Gastroenterologist",
    "Geophysicist",
    "Glazier",
    "Golfer",
    "Graphic Pre-press Trades Worker",
    "Greenkeeper",
    "Gunsmith",
    "Gymnastics Coach or Instructor",
    "Helicopter Pilot",
    "Historian",
    "Homoeopath",
    "Horse Breeder",
    "Horse Riding Coach or Instructor",
    "Hydrographer",
    "Importer or Exporter",
    "Information and Organisation Professionals nec",
    "Insurance Agent",
    "Insurance Investigator",
    "Insurance Loss Adjuster",
    "Interior Decorator",
    "Interpreter",
    "Jeweller",
    "Jockey",
    "Joiner",
    "Kennel Hand",
    "Landscape Gardener",
    "Librarian",
    "Lifeguard",
    "Locksmith",
    "Maintenance Planner",
    "Manufacturer",
    "Marine Transport Professionals nec",
    "Mathematician",
    "Meat Inspector",
    "Mine Deputy",
    "Minister of Religion",
    "Natural and Physical Science Professionals nec",
    "Naturopath",
    "Neurologist",
    "Newspaper or Periodical Editor",
    "Nutritionist",
    "Obstetrician and Gynaecologist",
    "Optical Dispenser (Aus) / Dispensing Optician (NZ)",
    "Orthoptist",
    "Orthotist or Prosthetist",
    "Other Sports Coach or Instructor",
    "Other Sports Official",
    "Otorhinolaryngologist",
    "Paediatrician",
    "Painter",
    "Painter (Visual Arts)",
    "Painting Trades Worker",
    "Panelbeater",
    "Park Ranger",
    "Patents Examiner",
    "Pathology Collector",
    "Penetration Tester",
    "Personal Assistant",
    "Pet Groomer",
    "Physicist",
    "Plumbing Inspector",
    "Podiatrist",
    "Power Generation Plant Operator",
    "Primary Products Inspectors nec",
    "Public Relations Professional",
    "Real Estate Agency Principal (Aus) / Real Estate Agency Licensee (NZ)",
    "Real Estate Agent",
    "Real Estate Representative",
    "Retail Buyer",
    "Rheumatologist",
    "Safety Inspector",
    "Sculptor",
    "Shearer",
    "Ship's Master",
    "Shipwright",
    "Singer",
    "Snowsport Instructor",
    "Social Professionals nec",
    "Sports Umpire",
    "Sportspersons nec",
    "Statistician",
    "Stock and Station Agent",
    "Stockbroking Dealer",
    "Stonemason",
    "Swimming Coach or Instructor",
    "Technical Cable Jointer",
    "Tennis Coach",
    "Training and Development Professional",
    "Translator",
    "Tree Worker",
    "Upholsterer",
    "Urban and Regional Planner",
    "Urologist",
    "Valuer",
    "Video Producer",
    "Visual Arts and Crafts Professionals nec",
    "Wholesaler",
    "Wool Buyer",
    "Wool Classer",
    "Workplace Relations Adviser",
    "Youth Worker",
    "Zookeeper",
  ],
};

/**
 * Flat list of all 691 occupations
 */
export const ALL_ELIGIBLE_OCCUPATIONS: string[] = Object.values(
  CATEGORIZED_OCCUPATIONS
).flat();

/**
 * Helper to search whether a role or term matches any eligible occupation
 */
export function findEligibleOccupation(query: string): {
  role: string;
  category: string;
} | null {
  const q = query.trim().toLowerCase();
  if (!q || q.length < 3) return null;

  // Words that are too generic to match alone
  const ignoreSet = new Set(["the", "and", "for", "with", "from", "list", "apply", "visa", "work", "role", "jobs"]);

  for (const [category, roles] of Object.entries(CATEGORIZED_OCCUPATIONS)) {
    for (const r of roles) {
      const lowerR = r.toLowerCase();

      // 1. Exact match
      if (lowerR === q) return { role: r, category };

      // 2. Query contains exact full role
      if (q.includes(lowerR)) return { role: r, category };

      // 3. Clean role without parentheses, e.g. "Early Childhood (Pre-primary School) Teacher" -> "early childhood teacher"
      const cleanR = lowerR
        .replace(/\([^)]*\)/g, "")
        .replace(/\bnec\b/g, "")
        .replace(/\s+/g, " ")
        .trim();

      if (cleanR.length >= 4 && !ignoreSet.has(cleanR)) {
        // Check if query contains cleaned role
        const regex = new RegExp(`\\b${cleanR.replace(/[-/\\^$*+?.()|[\]{}]/g, "\\$&")}\\b`, "i");
        if (regex.test(q)) return { role: r, category };
      }
    }
  }

  return null;
}
